BankingWebsite/Controllers/TransactionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BankingWebsite.Models;

namespace BankingWebsite.Controllers
{
    public class TransactionsController : Controller
    {
        private masterEntities1 db = new masterEntities1();

        // GET: Transactions
        public ActionResult Index()
        {
            var transactions = db.Transactions.Include(t => t.Card).Include(t => t.Card1);
            return View(transactions.ToList());
        }

        // GET: TransactionHistory
        public ActionResult PreTransactionHistory(int? id)
        {
            return View(db.Cards.Where(a => a.accountholder.ToString() == id.ToString()).ToList());
        }

        // GET: TransactionHistory
        public ActionResult TransactionHistory(int? id)
        {
            ViewBag.cardID = id.ToString();
            return View(db.Transactions.Where(w => w.toAccount == id || w.fromAccount == id).Include(t => t.Card).Include(t => t.Card1).ToList());
        }

        // GET: Transactions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transaction transaction = db.Transactions.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            return View(transaction);
        }

        // GET: Transactions/Create
        public ActionResult Create()
        {
            string ahID = Session["ahID"].ToString();

            ViewBag.fromAccount = new SelectList(db.Cards.Where(c => c.accountholder.ToString() == ahID), "cardID", "cardNo");
            ViewBag.toAccount = new SelectList(db.Cards.Where(c => c.accountholder.ToString() == ahID ), "cardID", "cardNo");
            return View();
        }

        // POST: Transactions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "transID,transDate,moneyIn,moneyOut,balance,fromAccount,toAccount")] Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                transaction.moneyIn = 0;

                transaction.balance = db.Cards.Single(c => c.cardID == transaction.fromAccount).balance - transaction.moneyOut;
                db.Cards.Single(c => c.cardID == transaction.fromAccount).balance = (decimal) transaction.balance;

                transaction.toBalance = db.Cards.Single(c => c.cardID == transaction.toAccount).balance + transaction.moneyOut;
                db.Cards.Single(c => c.cardID == transaction.toAccount).balance = (decimal)transaction.toBalance;

                transaction.transDate = DateTime.Now.Date;
                db.Transactions.Add(transaction);
                db.SaveChanges();
                return RedirectToAction("AccountHome/" + Session["ahID"], "AccountHolders1");
            }

            ViewBag.fromAccount = new SelectList(db.Cards, "cardID", "cardNo", transaction.fromAccount);
            ViewBag.toAccount = new SelectList(db.Cards, "cardID", "cardNo", transaction.toAccount);
            return View(transaction);
        }

        // GET: Transactions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transaction transaction = db.Transactions.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            ViewBag.fromAccount = new SelectList(db.Cards, "cardID", "cardNo", transaction.fromAccount);
            ViewBag.toAccount = new SelectList(db.Cards, "cardID", "cardNo", transaction.toAccount);
            return View(transaction);
        }

        // POST: Transactions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "transID,transDate,moneyIn,moneyOut,balance,fromAccount,toAccount")] Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                db.Entry(transaction).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.fromAccount = new SelectList(db.Cards, "cardID", "cardNo", transaction.fromAccount);
            ViewBag.toAccount = new SelectList(db.Cards, "cardID", "cardNo", transaction.toAccount);
            return View(transaction);
        }

        // GET: Transactions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transaction transaction = db.Transactions.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            return View(transaction);
        }

        // POST: Transactions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Transaction transaction = db.Transactions.Find(id);
            db.Transactions.Remove(transaction);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BankingWebsite/Views/Transactions/Create.cshtml
@model BankingWebsite.Models.Transaction

@{
    ViewBag.Title = "Create";
}

<div class="row">
    <div class="col-lg-2">
        <div id="wrapper">

            <!-- Sidebar -->
            <div id="sidebar-wrapper">
                <ul class="sidebar-nav">
                    <li class="sidebar-brand">
                        <a href=@Url.Action("AccountHome/"+ Session["ahID"],"AccountHolders1")>
                            Overview
                        </a>
                    </li>
                    <li>
                        <a href=@Url.Action("PreTransactionHistory/" + Session["ahID"] ,"Transactions")>Statements</a>
                    </li>
                    <li>
                        <a href=@Url.Action("Create","Transactions")>Transfer money</a>
                    </li>
                    <li>
                        <a href="#">Make payment</a>
                    </li>


                </ul>
            </div>
        </div>
        <!-- /#wrapper -->
        <!-- Menu Toggle Script -->
        <script>
$("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });</script>
    </div>
    <div class="generalblock col-lg-8">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="transactioncreate form-horizontal">
                <h4 style="padding-left:170px;">Transfer</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.transDate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @DateTime.Now.Date.ToShortDateString()
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.moneyOut, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.moneyOut, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.moneyOut, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.fromAccount, "fromAccount", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("fromAccount", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.fromAccount, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.toAccount, "toAccount", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("toAccount", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.toAccount, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BankingWebsite/Views/Transactions/Delete.cshtml
@model BankingWebsite.Models.Transaction

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Transaction</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.transDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.transDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.moneyIn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.moneyIn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.moneyOut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.moneyOut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.balance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.balance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Card.cardNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Card.cardNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Card1.cardNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Card1.cardNo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BankingWebsite/Views/Transactions/Details.cshtml
@model BankingWebsite.Models.Transaction

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Transaction</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.transDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.transDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.moneyIn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.moneyIn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.moneyOut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.moneyOut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.balance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.balance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Card.cardNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Card.cardNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Card1.cardNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Card1.cardNo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.transID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BankingWebsite/Views/Transactions/Edit.cshtml
@model BankingWebsite.Models.Transaction

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Transaction</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.transID)

        <div class="form-group">
            @Html.LabelFor(model => model.transDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.transDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.transDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.moneyIn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.moneyIn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.moneyIn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.moneyOut, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.moneyOut, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.moneyOut, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.balance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.balance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.balance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fromAccount, "fromAccount", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("fromAccount", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.fromAccount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.toAccount, "toAccount", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("toAccount", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.toAccount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BankingWebsite/Views/Transactions/Index.cshtml
@model IEnumerable<BankingWebsite.Models.Transaction>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.transDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.moneyOut)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.balance)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.toBalance)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Card.cardNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Card1.cardNo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.transDate)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.moneyOut)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.balance)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.toBalance)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Card.cardNo)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Card1.cardNo)
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.transID }) |
        @Html.ActionLink("Details", "Details", new { id = item.transID }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.transID })
    </td>
</tr>
}

</table>

BankingWebsite/Views/Transactions/PreTransactionHistory.cshtml
@{
    ViewBag.Title = "PreTransactionHistory";
}

<h3>Select account</h3>
@model IEnumerable<BankingWebsite.Models.Card>

@{
    ViewBag.Title = "AccountHome";
}

<div class="row">
    <div class="col-lg-2">
        <div id="wrapper">

            <!-- Sidebar -->
            <div id="sidebar-wrapper">
                <ul class="sidebar-nav">
                    <li class="sidebar-brand">
                        <a href=@Url.Action("AccountHome/"+ Session["ahID"],"AccountHolders1")>
                            Overview
                        </a>
                    </li>
                    <li>
                        <a href=@Url.Action("PreTransactionHistory/" + Session["ahID"] ,"Transactions")>Statements</a>
                    </li>
                    <li>
                        <a href=@Url.Action("Create","Transactions")>Transfer money</a>
                    </li>
                    <li>
                        <a href="#">Make payment</a>
                    </li>


                </ul>
            </div>
        </div>
        <!-- /#wrapper -->
        <!-- Menu Toggle Script -->
        <script>
$("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });</script>
    </div>
    <div class="col-lg-8">
        <div class="generalblock row">
            <h2>Transaction History</h2>
            <p>
                Select account
            </p>
        </div>

        <div class="generalblock row">
            <h3>Personal accounts</h3>
            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.accountName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.accountNumber)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.sortcode)
                    </th>
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.accountName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.accountNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.sortcode)
                        </td>
                        <td>
                            @Html.ActionLink("Transaction history", "TransactionHistory", new { id = item.cardID })
                        </td>
                    </tr>
                }

            </table>
        </div>

    </div>
    <div class="adbanner col-lg-2">
        <div class="adbanner">
            <p> Insert ad </p>
        </div>
    </div>

</div>

BankingWebsite/Views/Transactions/TransactionHistory.cshtml
@model IEnumerable<BankingWebsite.Models.Transaction>

@{
    ViewBag.Title = "View";
}

    <div class="row">
        <div class="col-lg-2">
            <div id="wrapper">

                <!-- Sidebar -->
                <div id="sidebar-wrapper">
                    <ul class="sidebar-nav">
                        <li class="sidebar-brand">
                            <a href=@Url.Action("AccountHome/"+ Session["ahID"],"AccountHolders1")>
                                Overview
                            </a>
                        </li>
                        <li>
                            <a href=@Url.Action("PreTransactionHistory/" + Session["ahID"] ,"Transactions")>Statements</a>
                        </li>
                        <li>
                            <a href=@Url.Action("Create","Transactions")>Transfer money</a>
                        </li>
                        <li>
                            <a href="#">Make payment</a>
                        </li>


                    </ul>
                </div>
            </div>
            <!-- /#wrapper -->
            <!-- Menu Toggle Script -->
            <script>
                $("#menu-toggle").click(function (e) {
                    e.preventDefault();
                    $("#wrapper").toggleClass("toggled");
                });</script>
        </div>
        <div class="col-lg-8">
            <h2>View</h2>
            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.transDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.moneyOut)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.balance)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.toBalance)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Card.cardNo)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Card1.cardNo)
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.transDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.moneyOut)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.balance)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.toBalance)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.Card.cardNo)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.Card1.cardNo)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.transID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.transID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.transID })
                </td>
            </tr>
                }


            </table>
        </div>
    </div>